services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "50051:50051"
    depends_on:
      - mongodb

  chat_service:
    build: ./chat_service
    container_name: chat_service
    ports:
      - "50052:50052"
    depends_on:
      - user_service

  file_service:
    build: ./file_service
    container_name: file_service
    ports:
      - "50053:50053"
    depends_on:
      - mongodb
    volumes:
      - uploads:/app/uploads

volumes:
  mongodbdata:
  uploads:
