services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "50051:50051"
    depends_on:
      - mongodb
    environment:
      - SECRET_KEY=${JWT_SECRET}

  chat_service:
    build: ./chat_service
    container_name: chat_service
    ports:
      - "50052:50052"
    depends_on:
      - user_service
    environment:
      - SECRET_KEY=${JWT_SECRET}

  file_service:
    build: ./file_service
    container_name: file_service
    ports:
      - "50053:50053"
    depends_on:
      - mongodb
    environment:
      - SECRET_KEY=${JWT_SECRET}
    volumes:
      - uploads:/app/uploads

  messaging_service:
    build: ./messaging_service
    container_name: messaging_service
    ports:
      - "50054:50054"
    depends_on:
      - mongodb
      - user_service
    environment:
      - SECRET_KEY=${JWT_SECRET}
      - MONGO_URI=mongodb://mongodb:27017
  


volumes:
  mongodbdata:
  uploads:
