# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x0b\x63hatservice\"!\n\x10\x45nterChatRequest\x12\r\n\x05token\x18\x01 \x01(\t\"5\n\x11\x45nterChatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9c\x01\n\x0b\x43hatService\x12J\n\tEnterChat\x12\x1d.chatservice.EnterChatRequest\x1a\x1e.chatservice.EnterChatResponse\x12\x41\n\x06Logout\x12\x1a.chatservice.LogoutRequest\x1a\x1b.chatservice.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTERCHATREQUEST']._serialized_start=35
  _globals['_ENTERCHATREQUEST']._serialized_end=68
  _globals['_ENTERCHATRESPONSE']._serialized_start=70
  _globals['_ENTERCHATRESPONSE']._serialized_end=123
  _globals['_LOGOUTREQUEST']._serialized_start=125
  _globals['_LOGOUTREQUEST']._serialized_end=155
  _globals['_LOGOUTRESPONSE']._serialized_start=157
  _globals['_LOGOUTRESPONSE']._serialized_end=207
  _globals['_CHATSERVICE']._serialized_start=210
  _globals['_CHATSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
